package com.github.aiderpmsi.pimsdriver.vaadin.utils.aop;

import com.vaadin.event.Action;

public class ActionHandlerEncloser implements Action.Handler {

	/** Autogenerated serialId */
	private static final long serialVersionUID = 8975728886110286674L;

	private final Action filter;
	
	private final ActionHandler handler;
	
	public ActionHandlerEncloser(final Action filter, final ActionHandler handler) {
		this.filter = filter;
		this.handler = handler;
	}

	@Override
	public Action[] getActions(final Object target, final Object sender) {
		if (target != null) {
			return new Action[] {filter};
		} else {
			return new Action[0];
		}
	}

	@Override
	public void handleAction(final Action action, final Object sender, final Object target) {
		if (action.equals(filter)) {
			handler.handleAction(action, sender, target);
		}
	}

	@FunctionalInterface
	public interface ActionHandler {
		public void handleAction(final Action action, final Object sender, final Object target);
	}
	
}
